### ISSUE TITLE
name "name" not defined

### ISSUE THREAD

**Issue by SparshMaheshwari** [ShubhamSonkesriya/Face-Recognition-Attendance-System#1]
getting an error -
name "name" not defined 
where as I tried to run the same code

**Comment by ShubhamSonkesriya** [comment]
On a vacation brother.
You’ll have to help yourself out, I guess.
Though, I would suggest you to look for the proper indentations, 90% of
time error occurs due to that.
Rest, the code works perfectly fine for now!

**Comment by ShubhamSonkesriya** [comment]
Look for proper indentations, 90% of time error occurs due to that.
Rest, Code works perfectly fine for now.
