### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by Venkat-Srinivasan-23** [ShubhamSonkesriya/Face-Recognition-Attendance-System#3]
When I try to run the code, it shows the following error message.

File "face_recog.py", line 74
    if True in matches:
    ^
IndentationError: unexpected indent

**Comment by ShubhamSonkesriya** [comment]
I looked into it and I have used this on multiple devices. Doesn’t show any errors as such. Might be some issue with the editor you are using!

**Comment by VenkatSrinivasan23** [comment]
I cloned your repo and and run the same code.
 
There is no issues with the editor, still the unexpected intent error occurs, I think the problem is with the code.

Can you please check it again with latest python version.

Tested environment:

Python 3.7.3
