### ISSUE TITLE
ModuleNotFoundError: No module named 'face_recognition'

### ISSUE THREAD

**Issue by syarwani03** [ShubhamSonkesriya/Face-Recognition-Attendance-System#4]
Traceback (most recent call last):
  File "face_recog.py", line 1, in <module>
    import face_recognition
ModuleNotFoundError: No module named 'face_recognition'
![DeepinScreenshot_select-area_20191129175936](https://user-images.githubusercontent.com/57739693/69860835-097f6f00-12d2-11ea-8ee4-8658040dbb24.png)

**Comment by ShubhamSonkesriya** [comment]
Please download face_recognition library.
